"""
Pydantic schemas for the synchronous ``POST /api/v1/review`` endpoint.
"""
from __future__ import annotations

import re

from pydantic import BaseModel, Field, field_validator

from app.core.exceptions import InvalidPRUrlError

# GitHub PR URL: https://github.com/{owner}/{repo}/pull/{number}
_PR_URL_PATTERN = re.compile(
    r"^https://github\.com/(?P<owner>[\w.\-]+)/(?P<repo>[\w.\-]+)/pull/(?P<number>\d+)/?$"
)


class ReviewRequest(BaseModel):
    """Request body for a synchronous PR review.

    Attributes:
        pr_url: Full GitHub Pull Request URL.
        language: Output language (``"zh"`` or ``"en"``). Default ``"zh"``.
    """

    pr_url: str = Field(
        ...,
        min_length=1,
        max_length=1024,
        description="Full GitHub Pull Request URL",
        examples=["https://github.com/owner/repo/pull/42"],
    )
    language: str = Field(
        default="zh",
        pattern=r"^(zh|en)$",
        description="Review report language: zh (Chinese) or en (English)",
    )

    @field_validator("pr_url")
    @classmethod
    def _validate_pr_url(cls, v: str) -> str:
        """Validate and normalise the PR URL."""
        url = v.strip()
        # Strip query params and fragments for validation
        base = url.split("?")[0].split("#")[0]
        if not _PR_URL_PATTERN.match(base):
            raise InvalidPRUrlError(
                f"Invalid GitHub PR URL: {url!r}. "
                f"Expected: https://github.com/{{owner}}/{{repo}}/pull/{{number}}"
            )
        return base


class ReviewResponse(BaseModel):
    """Response from a synchronous PR review.

    Attributes:
        pr_url: The original PR URL submitted.
        owner: GitHub repository owner.
        repo: GitHub repository name.
        pull_number: Pull Request number.
        pr_title: PR title fetched from GitHub.
        report: Markdown review report generated by the LLM.
        input_tokens: Number of prompt tokens consumed.
        output_tokens: Number of completion tokens generated.
        model: LLM model used for the review.
    """

    pr_url: str
    owner: str
    repo: str
    pull_number: int
    pr_title: str
    report: str
    input_tokens: int = 0
    output_tokens: int = 0
    model: str = ""
